# Stage 1: Build GROMACS from Git repository
# FROM ubuntu:24.04 as gromacs_builder

# # Install dependencies for GROMACS
# RUN apt-get update && \
#     apt-get install -y \
#     git \
#     cmake \
#     gcc \
#     g++ \
#     libfftw3-dev \
#     libopenmpi-dev \
#     libxml2-dev \
#     liblapack-dev \
#     libblas-dev \
#     && rm -rf /var/lib/apt/lists/*

# # Clone GROMACS repository (this layer will be cached unless the repo changes)
# RUN git clone -b freeze/v2025.1 https://github.com/sb-ncbr/gromacs.git /gromacs

# # Build GROMACS (this layer will be cached unless the source code changes)
# WORKDIR /gromacs
# RUN mkdir build
# WORKDIR /gromacs/build
# RUN cmake .. -DCMAKE_INSTALL_PREFIX=/opt/gromacs -DGMX_BUILD_OWN_FFTW=ON -DGMX_MPI=OFF -DGMX_GPU=OFF
# RUN make -j$(nproc)
# RUN make install

# Dockerfile.worker
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
    libfftw3-dev \
    libxml2-dev \
    liblapack-dev \
    libblas-dev \
    python3 \
    python3-venv \
    libvips \
    ncbi-blast+ \
    && rm -rf /var/lib/apt/lists/*

    
WORKDIR /app

ADD api /app/api
ADD cli /app/cli
RUN mkdir -p /app/tmp

RUN python3 -m venv /opt/venv \
    && ls -la \
    && /opt/venv/bin/pip install --upgrade pip setuptools wheel \
    && /opt/venv/bin/pip install --no-cache-dir -r ./api/requirements.txt -r ./cli/BAT2/requirements.txt

ENV PATH="/opt/venv/bin:${PATH}"

RUN chown -R 1000:1000 /app /opt/venv

USER 1000

# Entrypoint: start Celery worker
CMD ["celery", "-A", "api.app.celery", "worker", "--loglevel=debug", "--concurrency=4"]
